#!/bin/bash

# Check if iperf is already installed otherwise install it
if [ -f /usr/bin/iperf ]; then
    echo "iperf is already installed"
    exit 1
else
    apt install -y iperf3
fi

# Read server address from user
read -p "Enter the iperf server address: " SERVER_ADDRESS

# Read server port from user; default is 5201
read -p "Enter the iperf server port (default is 5201): " SERVER_PORT
if [ -z "$SERVER_PORT" ]; then
    SERVER_PORT=5201
fi

# Read how long the test needs to run; default is 20 seconds
read -p "Enter the duration of the test in seconds (default is 20s): " TEST_TIME
if [ -z "$DURATION" ]; then
    TEST_TIME=20
fi

# Read public key from user. The public key is generated by the iperf server.
read -p "Enter the public key address: " PUBLIC_KEY_ADDRESS


# Run iperf
echo "iperf3 --rsa-public-key-path $PUBLIC_KEY_ADDRESS --username iperf_client -c $SERVER_ADDRESS -t $TEST_TIME"

iperf3 --rsa-public-key-path $PUBLIC_KEY_ADDRESS --username iperf_client -c $SERVER_ADDRESS -t $TEST_TIME